import turtle

a = turtle.Screen()
t = turtle.Turtle()
turtle.bgcolor("yellow")
t.color('black', 'yellow')
t.begin_fill()
t.penup()
t.goto(0, -150)
t.pendown()
t.circle(180)
t.end_fill()
t.penup()
t.goto(-60, 100)
t.dot(25)
t.penup()
t.goto(60, 100)
t.dot(25)
t.penup()
t.goto(-90, -25)
t.pendown()
t.setheading(-60)
t.circle(100, 120)
